export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export WORKSPACE=$HOME/Workspace
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$WORKSPACE/heyhey/hey/bin
export PATH=$PATH:$WORKSPACE/config/dotemacs/bin
